---
- name: "Updating the guest operating system."
  ansible.builtin.apt:
    force_apt_get: true
    name: "*"
    state: latest     # noqa package-latest
    update_cache: "yes"
- name: "Installing additional packages."
  ansible.builtin.apt:
    name:
      - acl
      - bash-completion
      - ca-certificates
      - curl
      - git
      - gnupg
      - lvm2
      - net-tools
      - netcat
      - nfs-common
      - python3.11
      - python3-pip
      - python-is-python3
      - unzip
      - wget
    state: latest     # noqa package-latest

- name: Install resolv.conf
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
