---
templatePrefix: ubuntu-k8s
vsphere:
  cpu: 4
  ram: 16384
iso:
  path: "[isostore] linux/ubuntu"
  file: ubuntu-22.04.3-live-server-amd64.iso
  checksum: sha256:a4acfda10b18da50e2ec50ccaf860d7f20b389df8765611142305c0e911d16fd