---
- name: Prepare the image
  become: true
  become_method: sudo
  debugger: never
  gather_facts: true
  hosts: all
  roles:
    - base
    - users
    - configure
    - clean

  handlers:
    - name: Update GRUB
      ansible.builtin.command: update-grub
      listen: "update-grub"
      changed_when: true
